try {

    console.log(" this is the try block ")
    console.log(a);
}

catch (error) {
    console.log(" error in the file "+error)
}


